server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min_spare: 5

spring:
  application:
    name: config-server # ?? ??????? ??
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pollar-bookshop/config-repo
          default-label: main # ??? ? ??? ?? ????? main ????? ?? ???? ????.
          timeout: 5 # ?? ????? ??? ?? ??
          clone-on-start: true # ?? ????? ?? ???? ??? ??? ?? ??? ??
          force-pull: true # ?? ???? ?? ???? ?? ?? ??? ?? ?????? ????

logging:
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

#info:
#  system: Polar Bookshop

management:
  endpoints:
    web:
      exposure:
#        include: configprops, env, health, heapdump, info, loggers, mappings, prometheus
        include: health, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
#  info:
#    env:
#      enabled: true
#    java:
#      enabled: true
#    os:
#      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}