server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min_spare: 5

spring:
  application:
    name: config-server # ?? ??????? ??
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pollar-bookshop/config-repo
          default-label: main # ??? ? ??? ?? ????? main ????? ?? ???? ????.
          timeout: 5 # ?? ????? ??? ?? ??
          clone-on-start: true # ?? ????? ?? ???? ??? ??? ?? ??? ??
          force-pull: true # ?? ???? ?? ???? ?? ?? ??? ?? ?????? ????

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true